version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: $UID
        GID: $GID
    container_name: "peshtaxta-web"
    image: itachiuchixa/peshtaxta
    environment:
      TZ: ${TIMEZONE:-Asia/Tashkent}
      DB_DRIVER: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DATABASE_URL: postgres://admin:admin@postgres:5432/peshtaxta
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - mode: host
        target: 8080
        published: 8080

  postgres:
    container_name: "peshtaxta-postgres"
    environment:
      TZ: ${TIMEZONE}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${DB_DBNAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    image: postgres:13-alpine
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
    volumes:
      - ./docker/keycloak/custom-theme:/opt/keycloak/themes/custom-theme
    ports:
      - mode: host
        target: 8080
        published: 8088

